const questions = {
  level1: [
    {
      title: "Level 1",
      questionDescription: "Immigration",
      correctAnswer: "Imigração",
      choices: ["Emigração", "Imigração", "Importação"],
      correctResultMessage: "Well done!",
    },
    {
      title: "Level 1",
      questionDescription: "Arrival",
      correctAnswer: "Chegada",
      choices: ["Partida", "Chegada", "Alfândega"],
      correctResultMessage: "Well done!",
    },
    {
      title: "Level 1",
      questionDescription: "Luggage",
      correctAnswer: "Bagagem",
      choices: ["Bagagem", "Lugar", "Chegada"],
      correctResultMessage: "Well done!",
    },
    {
      title: "Level 1",
      questionDescription: "Baggage claim",
      correctAnswer: "Retirada de bagagem",
      choices: ["Retirada de bagagem", "Depósito de bagagem", "Bagagem de mão"],
      correctResultMessage: "Well done!",
    },
    {
      title: "Level 1",
      questionDescription: "Gate",
      correctAnswer: "Portão",
      choices: ["Saída", "Entrada", "Portão"],
      correctResultMessage: "Well done!",
    },
    {
      title: "Level 1",
      questionDescription: "Boarding Pass",
      correctAnswer: "Cartão de embarque",
      choices: ["Controle passaporte", "Cartão de embarque", "Passagem aérea"],
      correctResultMessage: "Well done!",
    },
    {
      title: "Level 1",
      questionDescription: "Flight Number",
      correctAnswer: "Número do vôo",
      choices: ["Número do vôo", "Número do assento", "Número do portão"],
      correctResultMessage: "Well done!",
    },
    {
      title: "Level 1",
      questionDescription: "Custom",
      correctAnswer: "Alfândega",
      choices: ["Alfândega", "Companhia aérea", "Serviço ao cliente"],
      correctResultMessage: "Well done!",
    },
    {
      title: "Level 1",
      questionDescription: "Tourist visa",
      correctAnswer: "Visto de turista",
      choices: ["Visto de trabalho", "Visto de estudante", "Visto de turista"],
      correctResultMessage: "Well done!",
    },
    {
      title: "Level 1",
      questionDescription: "Departure",
      correctAnswer: "Partida",
      choices: ["Despedida", "Departamento", "Partida"],
      correctResultMessage: "Well done!",
    },
  ],
  level2: [
    {
      title: "Level 2",
      questionDescription: "Where is the Immigration?",
      correctAnswer: "Onde é a imigração?",
      choices: ["Onde é a alfândega?", "O que é a imigração?", "Onde é a imigração?"],
      correctResultMessage: "Well done!",
    },
    {
      title: "Level 2",
      questionDescription: "What time is your arrival?",
      correctAnswer: "Que horas é a sua chegada?",
      choices: ["Que horas é a sua partida?", "Que horas é a sua chegada?", "Onde fica sua chegada?"],
      correctResultMessage: "Well done!",
    },
    {
      title: "Level 2",
      questionDescription: "My luggage was lost",
      correctAnswer: "Minha bagagem foi perdida",
      choices: ["Meu lugar foi perdido", "A bagagem foi perdida", "Minha bagagem foi perdida"],
      correctResultMessage: "Well done!",
    },
    {
      title: "Level 2",
      questionDescription: "Go downstairs for baggage claim",
      correctAnswer: "Desça as escadas para retirada de bagagem",
      choices: ["Vire a direita para depósito de bagagem", "Desça as escadas para retirada de bagagem", "Leve a sua bagagem de mão"],
      correctResultMessage: "Well done!",
    },
    {
      title: "Level 2",
      questionDescription: "Exit at gate 10",
      correctAnswer: "Saída no portão 10",
      choices: ["Saída no portão 10", "Espere no portão 10", "Saída às 10 horas"],
      correctResultMessage: "Well done!",
    },
    {
      title: "Level 2",
      questionDescription: "Here is my boarding pass",
      correctAnswer: "Aqui está meu cartão de embarque",
      choices: ["Guardei o seu cartão de embarque", "Procure o nosso cartão de embarque", "Aqui está meu cartão de embarque"],
      correctResultMessage: "Well done!",
    },
    {
      title: "Level 2",
      questionDescription: "What is your flight number?",
      correctAnswer: "Qual é o seu número de vôo?",
      choices: ["Qual o seu número de assento?", "Quando é o seu vôo?", "Qual é o seu número de vôo?"],
      correctResultMessage: "Well done!",
    },
    {
      title: "Level 2",
      questionDescription: "Nothing to declare at custom",
      correctAnswer: "Nada a declarar na alfândega",
      choices: ["Preciso passar na alfândega", "Nada a declarar na alfândega", "Declaração de consumo"],
      correctResultMessage: "Well done!",
    },
    {
      title: "Level 2",
      questionDescription: "Your tourist visa has expired",
      correctAnswer: "Seu visto de turista expirou",
      choices: ["Seu visto de turista expirou", "Seu visto de trabalho expirou", "Seu visto de estudante está válido"],
      correctResultMessage: "Well done!",
    },
    {
      title: "Level 2",
      questionDescription: "Go to the departure area",
      correctAnswer: "Vá para a área de partida",
      choices: ["Vá para o departamento", "Vá para a área de partida", "Vamos para a área de chegada"],
      correctResultMessage: "Well done!",
    },
  ]
}

export default questions;
